---

- include: minecraft.yml
  when: minecraft_server == 'minecraft'

- include: spigot.yml
  when: minecraft_server == 'spigot'

- name: agree to EULA
  lineinfile:
    dest: "{{ deploy_helper.shared_path }}/eula.txt"
    regexp: '^eula='
    line: 'eula={{ minecraft_eula_accept | lower }}'
    create: true
    mode: '0644'
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
  notify:
    - enable service

- name: check that log base directory exists
  file:
    path: "/var/log/minecraft"
    state: directory
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: 0755
  when:
    minecraft_external_log_conf is defined and
    minecraft_external_log_conf.fileName is defined

- name: external logging config
  template:
    src: "{{ minecraft_external_log_conf.template | default('log4j2.xml.j2') }}"
    dest: "{{ deploy_helper.shared_path }}/{{ minecraft_external_log_conf.conf_file }}"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: 0600
  when:
    minecraft_external_log_conf is defined
  notify:
    - restart Minecraft
