---
dependency:
  name: galaxy

driver:
  name: docker

scenario:
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
#    - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  directory: ../resources/tests/
  additional_files_or_dirs:
    - ${MOL_TESTINFRA_ADDITIONAL_TESTS:-../tests_empty}
  lint:
    name: flake8
  options:
      junit-xml: ${MOL_TESTINFRA_UNIT_REPORT}
