---
- name: "refresh plugin release"
  include_tasks: handlers/plugin_links.yml
  notify:
    - restart Minecraft

- name: reload systemd units
  systemd:
    daemon_reload: yes

- name: restart Minecraft
  service:
    name: "{{ minecraft_service_name }}"
    state: restarted

- name: enable service
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - "{{ minecraft_service_name }}.service"
    - "{{ minecraft_service_name }}.socket"
