---

- name: define plugin directories
  set_fact:
    plugin_sources: "{{ minecraft_plugins }}/current"
    plugin_target_link: "{{ minecraft_plugins }}/shared"

- name: "Find All Plugin *.jar files from the current Release"
  find:
    paths: "{{ plugin_sources }}"
    file_type: "file"
    patterns: "*.jar"
  register: "jarfiles"

- name: "Recreate symlinks"
  file:
    src: '{{ item.path }}'
    dest: "{{ item.path | regex_replace(plugin_sources, plugin_target_link ) }}"
    state: link
    force: true
  with_items: "{{ jarfiles.files }}"
  notify:
    - restart Minecraft

- name: "Recursively find plugin config directories"
  find:
    paths: "{{ plugin_sources }}"
    file_type: "directory"
  register: "plugindirectories"

- name: copying file with owner and permissions
  synchronize:
    src: '{{ item.path }}/'
    dest: "{{ item.path | regex_replace(plugin_sources, plugin_target_link ) }}/"
    dirs: true
    recursive: true
    rsync_opts:
      - "--chown={{ minecraft_user }}:{{ minecraft_group }}"
  delegate_to: "{{ inventory_hostname }}"
  with_items: "{{ plugindirectories.files }}"