---
dependency:
  name: galaxy
  options:
    role-file: ./molecule/resources/playbooks/requirements.yml
platforms:
  - name: instance
    image: ${MOL_IMAGE:-"solita/ubuntu-systemd:18.04"}
    groups:
      - minecraftserver
    command: ${MOL_INSTANCE_COMMAND:-"/sbin/init"}
    security_opts:
      - seccomp=unconfined
    capabilities:
      - SYS_ADMIN
    tmpfs: ${MOL_INSTANCE_TEMPFS:-["/tmp","/run","/run/lock"]}
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  inventory:
    group_vars:
      minecraftserver:
        user_accept_minecraft_eula: ${user_accept_minecraft_eula:-"false"}
        mc_version: ${MC_VERSION:-"latest"}
        minecraft_server: ${MC_SERVER_TYPE:-"minecraft"}
        jdk_used_version: ${JDK_VERSION:-"11"}
  playbooks:
    converge: ../resources/playbooks/playbook.yml
  lint:
    enabled: false
    name: ansible-lint
    options:
      x:
        - ANSIBLE0006
        - ANSIBLE0010
        - ANSIBLE0011
        - ANSIBLE0016
scenario:
  name: ci_single_container
